language: node_js

node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings_app

node_js:  
  - "9.4"

before_script:
  - psql -c 'create database  greetings_app' -U postgres
  - psql -U postgres -d greetings_app -a -f greetings_app.sql

services:
  - postgresql  
