language: node_js

node_js:
  - "v12.18.3"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings_testing

before_script:
  - psql -c 'create database  greetings_testing' -U postgres
  - psql -U postgres -d greetings_testing -a -f greetings_app.sql

services:
  - postgresql  
